server:
  port: 8050
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud-takeout?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
