server:
  port: 8020
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud-takeout?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.meng.cloud.user.entity

